/**
 * Action Items Service — AI-Generated PRM Suggestions (Server-only)
 *
 * Uses OpenAI's gpt-4o to analyze recent interactions with a contact
 * and generate 0-3 actionable suggestions (follow-ups, thank-yous,
 * check-ins, etc.). These become the "nudges" that make the PRM proactive.
 */

import { getOpenAI } from "@/lib/openai";
import { Contact, Interaction } from "@/lib/types";

/**
 * Describes a single action item generated by the AI.
 * This structure is what we ask GPT to return in its JSON response.
 */
interface ActionItem {
  /** The suggestion type — must match one of the allowed Suggestion.type values */
  type: "follow_up" | "thank_you" | "check_in" | "drop_email" | "pre_meeting_brief";
  /** Short, user-facing title for the suggestion card */
  title: string;
  /** Longer explanation of why this action is recommended */
  body: string;
  /** Priority from 1 (low) to 5 (high) */
  priority: number;
}

/**
 * Generates 0-3 actionable suggestions for a contact based on recent interactions.
 *
 * Prompt design:
 *  - The system prompt establishes the AI as a proactive PRM assistant and
 *    defines the exact JSON schema it must return. By specifying the schema
 *    in the prompt, we get structured output without needing function calling.
 *  - We provide the contact's name, company, and title for personalization.
 *  - We include the last 5 interactions (summaries + dates) to give the AI
 *    enough context to make informed suggestions without overwhelming it.
 *  - The AI is instructed to return 0 items if no action is needed, preventing
 *    spam suggestions. It should return at most 3 items.
 *  - We use gpt-4o (not mini) because generating good suggestions requires
 *    nuanced reasoning about relationship dynamics and timing.
 *
 * Parsing:
 *  - The response is expected to be a JSON array of ActionItem objects.
 *  - We extract JSON from the response (handling markdown code blocks if present).
 *  - If parsing fails, we return an empty array rather than throwing,
 *    because a failed suggestion generation shouldn't break the sync pipeline.
 *
 * @param contact - The contact to generate action items for.
 * @param interactions - Recent interactions with this contact (we use the last 5).
 * @returns An array of 0-3 action items.
 */
export async function generateActionItems(
  contact: Contact,
  interactions: Interaction[]
): Promise<ActionItem[]> {
  /* Take only the 5 most recent interactions to keep the prompt concise */
  const recentInteractions = interactions.slice(0, 5);

  /*
   * System prompt: defines the AI's role, the output schema, and the rules
   * for when (and when not) to suggest actions.
   */
  const systemPrompt = `You are a proactive personal PRM assistant. Your job is to analyze a user's recent interactions with a contact and suggest 0-3 actionable next steps.

Return a JSON array of action items. Each item must have this exact structure:
{
  "type": "follow_up" | "thank_you" | "check_in" | "drop_email" | "pre_meeting_brief",
  "title": "Short action title (under 60 chars)",
  "body": "1-2 sentence explanation of why this action is recommended",
  "priority": 1-5
}

Rules:
- Return an empty array [] if no action is needed right now.
- Maximum 3 suggestions per contact.
- "follow_up": suggest when a conversation was left open or needs a response.
- "thank_you": suggest after someone did something helpful.
- "check_in": suggest when it's been a while since the last interaction.
- "drop_email": suggest a casual reach-out to maintain the relationship.
- "pre_meeting_brief": suggest when there's an upcoming meeting with this contact.
- Be specific — reference actual interaction content in your suggestions.
- Set priority 4-5 for time-sensitive items, 1-2 for nice-to-haves.

Return ONLY the JSON array, no other text.`;

  /*
   * User message: provides the contact context and interaction history.
   * We format interactions as a numbered list with date, type, and summary.
   */
  const interactionList = recentInteractions
    .map(
      (i, idx) =>
        `${idx + 1}. [${i.occurred_at}] ${i.type.replace("_", " ")} — Subject: "${i.subject}" — Summary: ${i.ai_summary || i.snippet || "No summary"}`
    )
    .join("\n");

  const userMessage = `Contact: ${contact.name}
Company: ${contact.company || "Unknown"}
Title: ${contact.title || "Unknown"}

Recent interactions (newest first):
${interactionList || "No recent interactions found."}

Based on these interactions, what actions should the user take?`;

  /* Call gpt-4o for nuanced relationship reasoning */
  const response = await getOpenAI().chat.completions.create({
    model: "gpt-4o",
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userMessage },
    ],
    max_tokens: 500,
    temperature: 0.4, // Slightly creative but mostly consistent
  });

  const content = response.choices[0]?.message?.content?.trim() ?? "[]";

  /*
   * Parse the JSON response.
   * The model might wrap the JSON in markdown code blocks (```json ... ```),
   * so we strip those if present before parsing.
   */
  try {
    const cleaned = content.replace(/^```(?:json)?\s*/, "").replace(/\s*```$/, "");
    const items: ActionItem[] = JSON.parse(cleaned);

    /* Validate and filter: ensure each item has the required fields */
    return items.filter(
      (item) =>
        item.type &&
        item.title &&
        item.body &&
        typeof item.priority === "number"
    );
  } catch {
    /* If JSON parsing fails, return empty array rather than crashing the pipeline */
    console.error("Failed to parse action items response:", content);
    return [];
  }
}
